import './globals.css'
import { Pathway_Gothic_One } from 'next/font/google';
import { Raleway } from 'next/font/google';

const gothic = Pathway_Gothic_One({
  subsets: ["latin-ext"],
  variable: "--font-gothic",
  weight: '400'
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ['400', '500', '600', '700', '800'],

});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${gothic.variable} overflow-x-hidden font-gothic ${raleway.variable} font-raleway`}>
      <body>{children}</body>
    </html>
  )
}
